### ISSUE TITLE
Identitfy MIRA and PetriNet differences

### ISSUE THREAD

**Issue by YohannParis** [DARPA-ASKEM/model-transform#4]
- Identify the strengths, weaknesses, and differences of MIRA and PetriNet model frameworks.
- Meet with TA2 (UofF and HMS) to verify information

**Comment by bencodrington** [comment]
- From Florida’s perspective, “SBML -> MIRA -> Petri Net” is roughly equivalent to “Gromet -> BiLayer -> Petri Net”. Both are valid pipelines.
- From Florida’s perspective, there’s a lot of redundancy between MIRA templates and WiringDiagrams, one of the structures that Catlab supports.
  - Note that Ben G. wasn’t here to defend MIRA and I suspect in practice there are very real practical benefits to each of these “roughly equivalent” systems

Which representations for which operations?
Compose and Stratify: **Catlab** level because of their type system.
Search and Comparison: **MMT** because elements are grounded in context (e.g. there could be nuanced differences between multiple infected populations).
Sustain(keep your model up to date with new daily publications and data. More useful in fields like molecular biology where many discrete facts are published each day): **MMT**.
Comparison: Level of granularity and whether the model is decomposed or a hairball is more important than Petri vs. MMT.
Model space exploration: no existing MMT endpoint but could be done.
Extension (adding/removing components): Suggesting extensions from background knowledge? **MMT**. Manually adding components? **Petri**.

**Comment by YohannParis** [comment]
Thank you for completing this task properly @bencodrington!
I knew I could count on your need to keep your inbox/todo list nice and tidy like me :)
